data()

#methond a
install.packages("memisc")
library (memisc)
#get a data set
x <- data.set(artData)
typeof (x)
print(x)
#Generate a codebook based on the data set
codebook (x)
#Shows the attributes of the codebook and some digital features
summary (x)

#method b
install.packages("dataMaid")
library(dataMaid)
install.packages("rmarkdown")
library(rmarkdown)
data(bigPresidentData)
#Generate a codebook based on the data set
makeCodebook(bigPresidentData)
#Autogenerated data summary from dataMaid
makeDataReport(data =bigPresidentData,replace = TRUE)

#method c
y <- data.set(exampleData)
class (exampleData)
sapply(exampleData,class)
#Shows the attributes of the codebook and some digital features
summary (exampleData)

